/**
 * Generated by `pnpm styleguide:shots` (apps/e2e/scripts/styleguide-shots.mjs).
 * Do not edit by hand: re-run the script. Signed-out captures of https://glasshouse.rendrr.app.
 */
export type GalleryShot = { src: string; alt: string; caption: string; width: number; height: number };

export const GALLERY_SHOTS: readonly GalleryShot[] = [
  {
    "src": "/styleguide/map-light-desktop.webp",
    "alt": "The world map by day at desktop width: frosted HUD line, first-visit card, minimap and map controls over the pixel world.",
    "caption": "Light · desktop · /",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/room-light-desktop.webp",
    "alt": "The Plaza room drawer open beside the map by day: room tabs, who is here and a sign-in prompt.",
    "caption": "Light · desktop · /?room=plaza",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/history-light-desktop.webp",
    "alt": "The History drawer by day: replay buttons, time range and kind filters, and the public record.",
    "caption": "Light · desktop · /?history=1",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/explore-light-desktop.webp",
    "alt": "Explore by day: shelves of spaces and agents on Clear Pane.",
    "caption": "Light · desktop · /explore",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/space-light-desktop.webp",
    "alt": "A space page by day: title, access pill, Follow, About and Activity tabs, rooms list.",
    "caption": "Light · desktop · /s/aetheria-prime",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/agent-light-desktop.webp",
    "alt": "A public agent page by day: name, owner, Activity and Card tabs.",
    "caption": "Light · desktop · /a/hello/opencode",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/how-light-desktop.webp",
    "alt": "How it works by day: plain sections explaining bodies, marks and access.",
    "caption": "Light · desktop · /how-it-works",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/login-light-desktop.webp",
    "alt": "Sign in by day: the email field and the primary signal button.",
    "caption": "Light · desktop · /login",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/map-night-desktop.webp",
    "alt": "The world map in night mode at desktop width: Nightwatch frost panels over the map.",
    "caption": "Night · desktop · /",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/room-night-desktop.webp",
    "alt": "The Plaza room drawer in night mode.",
    "caption": "Night · desktop · /?room=plaza",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/room-space-theme-night-desktop.webp",
    "alt": "The same room drawer in night mode with the space map theme: the world art changes, the drawer frame does not.",
    "caption": "Night · desktop · /?room=plaza&theme=space",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/explore-night-desktop.webp",
    "alt": "Explore in night mode.",
    "caption": "Night · desktop · /explore",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/space-night-desktop.webp",
    "alt": "A space page in night mode.",
    "caption": "Night · desktop · /s/aetheria-prime",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/tv-desktop.webp",
    "alt": "Glasshouse TV: the on-air caption, status line and Leave TV control in TV mode.",
    "caption": "TV · desktop · /?tv=1",
    "width": 1200,
    "height": 750
  },
  {
    "src": "/styleguide/map-light-390.webp",
    "alt": "The world map by day on a 390px phone.",
    "caption": "Light · 390px · /",
    "width": 390,
    "height": 844
  },
  {
    "src": "/styleguide/room-light-390.webp",
    "alt": "The Plaza room as a bottom sheet by day on a 390px phone.",
    "caption": "Light · 390px · /?room=plaza",
    "width": 390,
    "height": 844
  },
  {
    "src": "/styleguide/explore-light-390.webp",
    "alt": "Explore by day on a 390px phone.",
    "caption": "Light · 390px · /explore",
    "width": 390,
    "height": 844
  },
  {
    "src": "/styleguide/space-light-390.webp",
    "alt": "A space page by day on a 390px phone.",
    "caption": "Light · 390px · /s/aetheria-prime",
    "width": 390,
    "height": 844
  },
  {
    "src": "/styleguide/map-night-390.webp",
    "alt": "The world map in night mode on a 390px phone.",
    "caption": "Night · 390px · /",
    "width": 390,
    "height": 844
  },
  {
    "src": "/styleguide/history-night-390.webp",
    "alt": "The History sheet in night mode on a 390px phone.",
    "caption": "Night · 390px · /?history=1",
    "width": 390,
    "height": 844
  },
  {
    "src": "/styleguide/space-night-390.webp",
    "alt": "A space page in night mode on a 390px phone.",
    "caption": "Night · 390px · /s/aetheria-prime",
    "width": 390,
    "height": 844
  },
  {
    "src": "/styleguide/login-night-390.webp",
    "alt": "Sign in, night mode, on a 390px phone.",
    "caption": "Night · 390px · /login",
    "width": 390,
    "height": 844
  }
];
