import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { COLOR_ROLES, MODES, brandTheme, lockupSvg, markGeometry, markSvg, tokensCss } from "../tokens/index.js";

const cssPath = fileURLToPath(new URL("../tokens/tokens.css", import.meta.url));

describe("generated token files", () => {
  it("tokens.css is exactly what values.ts generates", () => {
    const css = tokensCss();
    if (process.env.UPDATE_BRAND === "1") writeFileSync(cssPath, css);
    expect(readFileSync(cssPath, "utf8")).toBe(css);
  });

  it("defines every role for :root and each data-mode", () => {
    const css = tokensCss();
    for (const mode of MODES) expect(css).toContain(`[data-mode="${mode}"] {`);
    for (const role of COLOR_ROLES) expect(css).toContain(`--gh-${role}:`);
    expect(css).toContain("@media (prefers-color-scheme: dark)");
    expect(css).toContain(":root:not([data-mode])");
  });

  it("pins the tokens to night inside a legacy page frame, except on tv", () => {
    const css = tokensCss();
    const at = css.indexOf(':root:not([data-mode="tv"]) [data-brand-legacy] {');
    expect(at).toBeGreaterThan(-1);
    const block = css.slice(at, css.indexOf("}", at));
    expect(block).toContain("--gh-ground: #0A0B14;");
    expect(block).toContain("--gh-ink: #E4E2F0;");
  });

  it("legacy dusk/lantern fall back to Nightwatch, not the old aoe amber", () => {
    const { dusk, lantern } = brandTheme().colors as unknown as { dusk: Record<string, string>; lantern: Record<string, string> };
    expect(dusk[950]).toContain("--g-dusk-950, 10 11 20");
    expect(lantern[400]).toContain("--g-lantern-400, 183 166 242");
    expect(JSON.stringify({ dusk, lantern })).not.toContain("232 184 109");
  });

  it("keeps the legacy dusk/lantern names alongside the semantic ones", () => {
    const colors = brandTheme().colors as Record<string, unknown>;
    for (const k of ["dusk", "lantern", "surface", "ink", "muted", "line", "signal", "human", "agent", "focus", "pane"]) {
      expect(colors).toHaveProperty(k);
    }
    // Tailwind's own sky-* palette is still used by pages; never shadow it.
    expect(colors).not.toHaveProperty("sky");
  });
});

describe("mark", () => {
  it("the lockup can take currentColor so one inline SVG follows the mode", () => {
    const svg = lockupSvg("light", "currentColor");
    expect(svg).toContain('stroke="currentColor"');
    expect(svg).toContain('fill="currentColor"');
    expect(svg.match(/fill="#E2542B"/g)).toHaveLength(1);
    expect(lockupSvg("light")).not.toContain("currentColor");
  });

  it("four panes in a square frame, one lit in signal", () => {
    const svg = markSvg("light");
    expect(svg).toContain('stroke="#0E1B2B"');
    expect(svg.match(/fill="#E2542B"/g)).toHaveLength(1);
    const { lit, stroke } = markGeometry();
    // Lit pane sits inside the top-right cell, clear of the mullions.
    expect(lit.x).toBeGreaterThan(23 + stroke / 2);
    expect(lit.x + lit.w).toBeLessThan(42 - stroke / 2);
    expect(lit.y + lit.h).toBeLessThan(23 - stroke / 2);
  });

  it("matches the snapshot", () => {
    expect(markSvg("light")).toMatchSnapshot();
    expect(markSvg("night", "small")).toMatchSnapshot();
  });
});

describe("DESIGN.md", () => {
  const designPath = fileURLToPath(new URL("../../../docs/design/DESIGN.md", import.meta.url));
  it("embeds the current contrast table", async () => {
    const { contrastTableMarkdown } = await import("../tokens/index.js");
    const start = "<!-- CONTRAST:START (generated by contrastTableMarkdown) -->";
    const end = "<!-- CONTRAST:END -->";
    const doc = readFileSync(designPath, "utf8");
    const table = contrastTableMarkdown();
    const i = doc.indexOf(start);
    const j = doc.indexOf(end);
    expect(i).toBeGreaterThan(-1);
    expect(j).toBeGreaterThan(i);
    const next = `${doc.slice(0, i + start.length)}\n${table}\n${doc.slice(j)}`;
    if (process.env.UPDATE_BRAND === "1") writeFileSync(designPath, next);
    expect(readFileSync(designPath, "utf8")).toBe(next);
  });
});
